Repository promisependingapis/twitch.js, pull requests merged in 2021-01, with the labels that each got.

#13 Merge To Release
  .eslintrc.json
  .github/dependabot.yml
  .github/workflows/eslint.yml
  .npmignore
  .prettierignore
  .prettierrc.json
  README.md
  package-lock.json
  package.json
  src/client/Client.js
  src/index.js
  src/sleept/RequestHandlers/Burst.js
  src/sleept/RequestHandlers/RequestHandler.js
  src/sleept/RequestHandlers/Sequential.js
  src/sleept/SLEEPTMananger.js
  src/sleept/SLEEPTMethods.js
  src/sleept/TwitchAPIError.js
  src/sleept/UserAgentManager.js
  src/structures/channels.js
  src/structures/users.js
  src/utils/AutoEndLog.js
  src/utils/Constants.js
  src/utils/DateParser.js
  src/utils/collection.js
  src/utils/index.js
  src/utils/logger.js
  src/utils/parser.js
  src/utils/util.js
Labels: Resolution: resolved, Type: bug, Type: enhancement

#16 Release beta 9
  .eslintignore
  .prettierignore
  .prettierrc.json
  README.md
  package-lock.json
  package.json
  src/client/Client.js
  src/sleept/APIRequest.js
  src/sleept/RequestHandlers/Burst.js
  src/sleept/RequestHandlers/Sequential.js
  src/sleept/SLEEPTMananger.js
  src/sleept/SLEEPTMethods.js
  src/sleept/UserAgentManager.js
  src/sleept/api/functions/chatters.js
  src/sleept/api/index.js
  src/sleept/api/twitchWebAPI.js
  src/structures/channels.js
  src/structures/index.js
  src/structures/users.js
  src/utils/AutoEndLog.js
  src/utils/Constants.js
  src/utils/collection.js
  src/utils/index.js
  src/utils/logger.js
Labels: Resolution: resolved, Type: bug, Type: enhancement

#17 Update beta 9 to beta 10
  README.md
  package-lock.json
  package.json
  src/sleept/SLEEPTMethods.js
  src/utils/Constants.js
Labels: Status: Awaiting Review, Type: enhancement

#18 Beta 11 because yes
  package-lock.json
  package.json
  src/client/Client.js
  src/sleept/SLEEPTMethods.js
  src/structures/users.js
Labels: Status: Awaiting Review, Type: enhancement

#20 Updated README.md
  README.md
Labels: Resolution: resolved

#19 Typpings for typescript.
  index.d.ts
Labels: Type: documentation, Type: enhancement, good first issue
